config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from root.sitemap import StaticSiteMap, DynamicSiteMap


sitemaps = {
    'static' : StaticSiteMap,
    'dynamic' : DynamicSiteMap,
    
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("root.urls")),
    path("courses/",include("courses.urls")),
    path("accounts/",include("accounts.urls")),
    path("accounts/",include("django.contrib.auth.urls")),
    path('robots.txt/', include("robots.urls")),
    path(
    "sitemap.xml/",
    sitemap,
    {"sitemaps": sitemaps},
    name="django.contrib.sitemaps.views.sitemap",
),
    path('captcha/', include('captcha.urls')),
    
]



urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root = settings.STATIC_ROOT)

courses/urls.py
from django.urls import path
from .views import *


app_name = 'courses'

urlpatterns = [
    path("", CourseListView.as_view(),name='courses'),
    path("category/<str:cat>",CourseListView.as_view(),name="course_cat"),
    path("teacher/<str:teacher>",CourseListView.as_view(),name="course_teacher"),
    path("search/",CourseListView.as_view(),name="course_search"),
    path("course-detail/<int:pk>",CourseDetailView.as_view(),name="course_detail"),
    path("<int:pk>",DeleteCommentView.as_view(),name="delete"),
    path("edit/comment/<int:pk>",CommentEditView.as_view(),name="edit"),
    path("comment/reply/<int:pk>",ReplyView.as_view(),name="reply"),
    # path("payment",PaymentView.as_view(),name="cart"),
    path("payment",vart,name="cart"),
]

root/urls.py
from django.urls import path
from .views import *



app_name = 'root'

urlpatterns = [
    path("",HomeView.as_view(),name="home"),
    path("about",about,name="about"),
    path("contact",contact,name="contact"),
    path("trainer",trainer,name="trainer"),
]

templates/course/cart.html
{% extends "base.html" %}
{% block 'title' %}payment{% endblock 'title' %}
{% block 'content' %}
<br><br><br><br><br><br><br><br><br>
{% for  product in cart %}

    <h5><p>{{product.product_object.title}}</p></h5>
    <h5><p>{{ product.product_object.price }}</p></h5>
    <h5><p>{{ product.product_object.all_quantity }}</p></h5>
    <h5><p><img src={{ product.product_object.image.url }}></p></h5>
  

{% endfor %}
<h5><p>--------------------</p></h5>
<a href="#"> payment and go to paymen site {{ cart.get_total_price_some_quantity }}</a>
<br>
<form method="post">
    {% csrf_token %}
    <button type="submit">Clear Cart</button>
</form> 
{% endblock 'content' %}

templates/course/comment_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form.as_p }}
    <input type="submit" value="Confirm">
</form>

templates/course/course-details.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}course{% endblock 'title' %}
{% block 'content' %}


  <main pk="main">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs" data-aos="fade-in">
      <div class="container">
        <h2>Course Details</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs -->

    <!-- ======= Cource Details Section ======= -->
    <section pk="course-details" class="course-details">
      <div class="container" data-aos="fade-up">

        <div class="row">
          <div class="col-lg-8">
            <img src={{course.image.url}} class="img-fluid" alt="">
            <h3>{{course.title}}</h3>
            <p>
              {{course.content}}
            </p><br>
            <div class="navigation-area">
              <div class="row">
                {% if next_course and previous_course %}
                <div class="col-lg-5 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' pk=previous_course.id %}><img class="img-fluid" src={{previous_course.image.url}} alt=""></a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' pk=previous_course.id %}><span class="lnr text-white lnr-arrow-left"></span></a>
                  </div>
                  <div class="detials">
                    <p>Prev Course</p>
                    <a href={% url 'courses:course_detail' pk=previous_course.id %}>
                      <h4>{{previous_course.title}}</h4>
                    </a>
                  </div>
                </div>
                <div class="col-lg-5 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                  <div class="detials">
                    <p>Next Post</p>
                    <a href={% url 'courses:course_detail' pk=next_course.id %}>
                      <h4>{{next_course.title}}</h4>
                    </a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' pk=next_course.id %}><span class="lnr text-white lnr-arrow-right"></span></a>
                  </div>
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' pk=next_course.id %}><img class="img-fluid" src={{next_course.image.url}} alt=""></a>
                  </div>
                </div>
                {% elif next_course %}
                <div class="col-lg-5 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                  <div class="detials">
                    <p>Next Post</p>
                    <a href={% url 'courses:course_detail' pk=next_course.id %}>
                      <h4>{{next_course.title}}</h4>
                    </a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' pk=next_course.id %}><span class="lnr text-white lnr-arrow-right"></span></a>
                  </div>
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' pk=next_course.id %}><img class="img-fluid" src={{next_course.image.url}} alt=""></a>
                  </div>
                </div>
                {% elif previous_course %}
                <div class="col-lg-5 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                  <div class="thumb">
                    <a href={% url 'courses:course_detail' pk=previous_course.id %}><img class="img-fluid" src={{previous_course.image.url}} alt=""></a>
                  </div>
                  <div class="arrow">
                    <a href={% url 'courses:course_detail' pk=previous_course.id %}><span class="lnr text-white lnr-arrow-left"></span></a>
                  </div>
                  <div class="detials">
                    <p>Prev Course</p>
                    <a href={% url 'courses:course_detail' pk=previous_course.id %}> 
                      <h4>{{previous_course.title}}</h4>
                    </a>
                  </div>
                </div>
                {% endif %}
              </div>
            </div><br>
            <div class="comments-area">
              <h4>{{comments.count}} Comments</h4>
              {% for comment in comments %}
              <div class="comment-list">
                <div class="single-comment justify-content-between d-flex">
                  <div class="user justify-content-between d-flex">
                    <div class="thumb">
                      <img src="img/blog/c1.jpg" alt="">
                    </div>
                    <div class="desc">
                      <h5><a href="#">{{comment.name}}</a></h5>
                      <p class="date">{{comment.created_date|date:"d M Y"}}</p>
                      <p class="comment">
                        {{comment.message}}
                      </p>
                      {% if request.user.is_authenticated and request.user.username == comment.name %}
                      <a type='button' href={% url 'courses:delete' pk=comment.id %}>Delete</a>
                      <a type='button' href={% url 'courses:edit' pk=comment.id %}>Edit</a>
                      {% endif %}
                    </div> 

                  </div>
                  <div class="reply-btn">
                    {% if request.user.is_authenticated %}
                    <p><a href={% url 'courses:reply' pk=comment.id %} class="btn-reply text-uppercase">reply</a></p>
                    {% endif %}
                    {% for rp in reply %}
                      {% if rp.which_comment.id == comment.id %}
                          <p>{{rp.name}}:{{rp.message}}</p>
                      {% endif %}
                    {% endfor %}
                  </div>
                </div>
              </div>
              {% endfor %}
            </div><br>
            <div class="comment-form" >
              <h4 align='center'>Leave a Comment</h4>
              {% if messages %}
                {% for message in messages %}
                  {{message}}
                {% endfor %}
              {% endif %}

            </div>
          </div>
          <div class="col-lg-4">

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Trainer</h5>
              <p><a href="#">{{course.teacher.info.username}}</a></p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Course Fee</h5>
              <p>{{course.price}}$</p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Available Seats</h5>
              <p>{{course.available_seat}}</p>
            </div>

            <div class="course-info d-flex justify-content-between align-items-center">
              <h5>Schedule</h5>
              <p>{{course.schedule|date:"D d M Y----H:i A"}}</p>
            </div>
            <div class="course-info d-flex justify-content-between align-items-center">
              <form method="post">
                {% csrf_token %}
                <input type="hidden" name="pk" value="{{course.id}}"> 
                <button type="submit">Add To Cart</button>
              

              <div class="input-group-prepend">
                      <button class="btn btn-outline-secondary btn-plus" type="button">+</button>
                  </div>
                  <input type="text" name="q" value="1" class="form-control text-center order-number" >
                  <div class="input-group-prepend">
                      <button class="btn btn-outline-secondary btn-minus" type="button">_</button>
                  </div>
              </div>
              {% comment %} <form method="post">
                {% csrf_token %}
                <input type="hidden" name="id" value="{{course.id}}"> 
                <button type="submit">Delete From Cart</button>
              </form> {% endcomment %}
              </form>
            </div>

          </div>
        </div>

      </div>
    </section><!-- End Cource Details Section -->

  </main><!-- End #main -->

 {% endblock 'content' %}

templates/course/courses.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load custom_tags %}
{% block 'title' %}course{% endblock 'title' %}
{% block 'content' %}


  <main id="main" data-aos="fade-in">

    <!-- ======= Breadcrumbs ======= -->
    <div class="breadcrumbs">
      <div class="container">
        <h2>Courses</h2>
        <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
      </div>
    </div><!-- End Breadcrumbs --><br>
    <div class="single-sidebar-widget search-widget" align="center">
      <form class="search-form" action={% url 'courses:course_search' %}>
          <input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Posts'">
          <button type="submit">click</button>
      </form>
    </div>

    <!-- ======= Courses Section ======= -->
    <section id="courses" class="courses">
      <div class="container" data-aos="fade-up">

        <div class="row" data-aos="zoom-in" data-aos-delay="100">
          {% for cr in courses  %}

          <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
            <div class="course-item">
              <img src={{cr.image.url}} class="img-fluid" alt="...">
              <div class="course-content">
                <div class="d-flex justify-content-between align-items-center mb-3">
                  {% for cat in cr.category.all  %}
                  <h4>{{cat.name}}</h4>
                  {% endfor %}
                  <p class="price">${{cr.price}}</p>
                </div>
                <form method="post">
                  {% csrf_token %}
                  <input type="hidden" name="pk" value="{{cr.id}}"> 
                  <button type="submit">Add To Cart</button>
                </form>

                <h3><a href="{% url 'courses:course_detail' pk=cr.id %}">{{cr.capt}}</a></h3>
                <p>{{cr.content|truncate2:3}}</p>
                <div class="trainer d-flex justify-content-between align-items-center">
                  <div class="trainer-profile d-flex align-items-center">
                    <img src={{cr.teacher.image.url}} class="img-fluid" alt="">
                    <span><a href={% url 'courses:course_teacher' teacher=cr.teacher.info.email %}>{{cr.teacher.info.email}}</a></span>
                  </div>
                  <div class="trainer-rank d-flex align-items-center">
                    <i class="bx bx-user"></i>&nbsp;{{cr.counted_views|ordinal}}
                    &nbsp;&nbsp;
                    <i class="bx bx-heart"></i>&nbsp;{{cr.counted_like}}
                  </div>
                  <span>{{cr.schedule|naturaltime}}</span>
                </div>
              </div>
            </div>
          </div> <!-- End Course Item-->
          {% endfor %}
       

        </div>

      </div>
    </section><!-- End Courses Section -->
    <div align="center" style="font-size:35px;">
      {% if  page_obj.has_next and page_obj.has_previous %}
      <a href="?page=1"><<</a>
      <a href="#">....</a>
      <a href="?page={{page_obj.previous_page_number}}"><</a>
      <a href="#">....</a>
      <a href="?page={{page_obj.next_page_number}}">></a>
      <a href="#">....</a>
      <a href="?page={{page_obj.paginator.num_pages}}">>></a>
      {% elif page_obj.has_next %}
      <a href="?page={{page_obj.next_page_number}}">></a>
      <a href="#">....</a>
      <a href="?page={{page_obj.paginator.num_pages}}">>></a>
      {% elif page_obj.has_previous %}
      <a href="?page=1"><<</a>
      <a href="#">....</a>
      <a href="?page={{page_obj.previous_page_number}}"><  </a>
      {% endif %}

    </div>

  </main><!-- End #main -->
  {% endblock 'content' %}

  

templates/course/edit.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}edit{% endblock 'title' %}
{% block 'content' %}
<br><br><br><br>
<form method='post'>
    {% csrf_token %}
<div class="form-group form-inline">
      <div class="form-group col-lg-6 col-md-12 name">
        <input type='hidden' name='which_course' value={{comment.which_course.id}}>
        <input type="hidden" class="form-control" name="name" placeholder="Enter Name"
          onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'" value={{comment.name}}>
      </div>
      <div class="form-group col-lg-6 col-md-12 email">
        <input type="hidden" class="form-control" name="email" placeholder="Enter email address"
          onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" value={{comment.email}}>
      </div>
    </div>
    <div class="form-group">
      <input type="text" class="form-control" name="subject" placeholder="Subject"
        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'" value="{{comment.subject}}">
    </div>
    <div class="form-group">
      <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required="">{{comment.message}}</textarea>
    </div>
    {% comment %} {{ form.as_p }} {% endcomment %}
    <button type='submit' class="primary-btn text-uppercase">Post Comment</button>
  </form>
<br><br><br><br>
{% endblock 'content' %}

templates/course/reply.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}reply{% endblock 'title' %}
{% block 'content' %}
<br><br><br><br>
<form method='post'>
    {% csrf_token %}
<div class="form-group form-inline">
      <div class="form-group col-lg-6 col-md-12 name">
        <input type='hidden' name='which_comment' value={{comment.id}}>
        <input type="text" class="form-control" name="name" placeholder="Enter Name"
          onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
      </div>
    </div>
    <div class="form-group">
      <textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
    </div>
    
    {% if messages %}
        {% for message in messages %}
             <p>{{message}}</p>
        {% endfor %}
    {% endif %}
    {% comment %} {{ form.as_p }} {% endcomment %}
    <button type='submit' class="primary-btn text-uppercase">Reply Comment</button>
  </form>
<br><br><br><br>
{% endblock 'content' %}